name: Notify Discord on PR Open

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: 'Discord notification'
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1288136629818490920/0IHaoC_8ZBRLdzw9JhOeJTllg3LA2OOK6OfgEV373rr2XLfZKY0SVmGO5bikyTaUvOpn/github
        uses: Ilshidur/action-discord@master
        with:
          args: '📣 @everyone รบกวนตรวจสอบ commits และ approve (ถ้าโอเค) ด้วยคับ✨ ➡️ ${{ github.event.pull_request.html_url }}'
